# Week 5 — Additional Models: Decision Tree and Random Forest

In this notebook, I tested Decision Tree and Random Forest regression models to predict California residential single-family property close prices. The goal is to compare these tree-based models against the Week 4 Linear Regression baseline.

In [15]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [16]:
train_df = pd.read_csv("train_residential_single_family_week3_no_outliers.csv")
test_df = pd.read_csv("test_residential_single_family_week3_no_outliers.csv")

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

Train shape: (128568, 57)
Test shape: (11914, 57)

In [17]:
numeric_features = [
    "LivingArea",
    "BedroomsTotal",
    "BathroomsTotalInteger",
    "LotSizeSquareFeet",
    "LotSizeAcres",
    "LotSizeArea",
    "YearBuilt",
    "GarageSpaces",
    "ParkingTotal",
    "Latitude",
    "Longitude",
    "Stories",
    "AssociationFee",
    "MainLevelBedrooms"
]

categorical_features = [
    "CountyOrParish",
    "City",
    "PostalCode",
    "HighSchoolDistrict",
    "Flooring",
    "AttachedGarageYN",
    "Levels",
    "PoolPrivateYN",
    "NewConstructionYN",
    "ViewYN",
    "FireplaceYN"
]

In [18]:
reference_only_cols = ["OriginalListPrice", "ListPrice", "DaysOnMarket", "price_per_sqft"]
reference_only_flags = [
    f"{c}_missing_flag" 
    for c in reference_only_cols 
    if f"{c}_missing_flag" in train_df.columns
]

target_derived_cols = ["log_ClosePrice"]

exclude_from_model = reference_only_cols + reference_only_flags + target_derived_cols

feature_numeric = numeric_features.copy()

for col in ["home_age", "log_LivingArea", "log_LotSizeSquareFeet"]:
    if col in train_df.columns:
        feature_numeric.append(col)

missing_flag_cols = [col for col in train_df.columns if col.endswith("_missing_flag")]
feature_numeric += missing_flag_cols

feature_numeric = list(dict.fromkeys([col for col in feature_numeric if col in train_df.columns]))
feature_categorical = [col for col in categorical_features if col in train_df.columns]

feature_numeric = [col for col in feature_numeric if col not in exclude_from_model]
feature_categorical = [col for col in feature_categorical if col not in exclude_from_model]

print("Number of numeric predictors:", len(feature_numeric))
print("Number of categorical predictors:", len(feature_categorical))

print("\nNumerical predictors:")
print(feature_numeric)

print("\nCategorical predictors:")
print(feature_categorical)

Number of numeric predictors: 32
Number of categorical predictors: 11

Numerical predictors:
['LivingArea', 'BedroomsTotal', 'BathroomsTotalInteger', 'LotSizeSquareFeet', 'LotSizeAcres', 'LotSizeArea', 'YearBuilt', 'GarageSpaces', 'ParkingTotal', 'Latitude', 'Longitude', 'Stories', 'AssociationFee', 'MainLevelBedrooms', 'home_age', 'log_LivingArea', 'log_LotSizeSquareFeet', 'LivingArea_missing_flag', 'BedroomsTotal_missing_flag', 'BathroomsTotalInteger_missing_flag', 'LotSizeSquareFeet_missing_flag', 'LotSizeAcres_missing_flag', 'LotSizeArea_missing_flag', 'YearBuilt_missing_flag', 'GarageSpaces_missing_flag', 'ParkingTotal_missing_flag', 'Latitude_missing_flag', 'Longitude_missing_flag', 'Stories_missing_flag', 'AssociationFee_missing_flag', 'MainLevelBedrooms_missing_flag', 'home_age_missing_flag']

Categorical predictors:
['CountyOrParish', 'City', 'PostalCode', 'HighSchoolDistrict', 'Flooring', 'AttachedGarageYN', 'Levels', 'PoolPrivateYN', 'NewConstructionYN', 'ViewYN', 'FireplaceYN']

In [19]:
X_train_raw = train_df[feature_numeric + feature_categorical].copy()
X_test_raw = test_df[feature_numeric + feature_categorical].copy()

y_train = train_df["ClosePrice"].copy()
y_test = test_df["ClosePrice"].copy()

print("X_train_raw shape:", X_train_raw.shape)
print("X_test_raw shape:", X_test_raw.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train_raw shape: (128568, 43)
X_test_raw shape: (11914, 43)
y_train shape: (128568,)
y_test shape: (11914,)

In [20]:
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer

for col in feature_categorical:
    # converts everything to string 
    X_train_raw[col] = X_train_raw[col].astype(str)
    X_test_raw[col] = X_test_raw[col].astype(str)

try:
    encoder = OneHotEncoder(
        handle_unknown='ignore',
        sparse_output=True
    )
except TypeError:
    encoder = OneHotEncoder(
        handle_unknown='ignore',
        sparse=True
    )

In [7]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", feature_numeric), # Don't change these numeric column, just keep them
        ("cat", encoder, feature_categorical) # onehotencode for categorial features
    ],
    remainder='drop'
)

X_train_processed = preprocessor.fit_transform(X_train_raw)
X_test_processed = preprocessor.transform(X_test_raw)

In [8]:
print("Raw X_train shape:", X_train_raw.shape)
print("Processed X_train shape:", X_train_processed.shape)
print("Raw X_test shape:", X_test_raw.shape)
print("Processed X_test shape:", X_test_processed.shape)
print("Data type:", type(X_train_processed))

Raw X_train shape: (128568, 43)
Processed X_train shape: (128568, 3889)
Raw X_test shape: (11914, 43)
Processed X_test shape: (11914, 3889)
Data type: <class 'scipy.sparse._csr.csr_matrix'>

#### **Train Decision Tree**

In [9]:
from sklearn.tree import DecisionTreeRegressor

decision_tree = DecisionTreeRegressor(
    max_depth=12,
    min_samples_leaf=50,
    random_state=42
)

In [10]:
decision_tree.fit(X_train_processed, y_train)

dt_pred = decision_tree.predict(X_test_processed)


print("Decision Tree model trained.")
print("Number of predictions:", len(dt_pred))
print("First 5 predictions:", dt_pred[:5])

Decision Tree model trained.
Number of predictions: 11914
First 5 predictions: [ 910625.6473167   530825.41605839  360148.25200918 1699969.04615385
  739257.04964871]

In [11]:
dt_r2 = r2_score(y_test, dt_pred)
dt_mae = mean_absolute_error(y_test, dt_pred)
dt_rmse = np.sqrt(mean_squared_error(y_test, dt_pred))

print("Decision Tree Results")
print("R²:", dt_r2)
print("MAE:", dt_mae)
print("RMSE:", dt_rmse)

Decision Tree Results
R²: 0.767819687493566
MAE: 249688.93182258972
RMSE: 436461.49968683365

In [12]:
dt_results = []

for max_depth in [6, 8, 10, 12, 15, 18]:
    for min_samples_leaf in [20, 50, 100, 200]:
        model = DecisionTreeRegressor(
            max_depth=max_depth,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )
        
        model.fit(X_train_processed, y_train)
        pred = model.predict(X_test_processed)
        
        r2 = r2_score(y_test, pred)
        mae = mean_absolute_error(y_test, pred)
        rmse = np.sqrt(mean_squared_error(y_test, pred))
        
        dt_results.append({
            "Model": "Decision Tree",
            "max_depth": max_depth,
            "min_samples_leaf": min_samples_leaf,
            "R2": r2,
            "MAE": mae,
            "RMSE": rmse
        })

dt_tuning_results = pd.DataFrame(dt_results)
dt_tuning_results.sort_values("R2", ascending=False).head(10)

,Model,max_depth,min_samples_leaf,R2,MAE,RMSE
20,Decision Tree,18,20,0.814337,211438.693273,390298.038735
16,Decision Tree,15,20,0.800382,223125.039107,404699.555558
21,Decision Tree,18,50,0.799606,221165.193494,405486.061425
17,Decision Tree,15,50,0.790254,229957.846291,414839.324568
22,Decision Tree,18,100,0.779992,234351.936635,424866.735634
18,Decision Tree,15,100,0.775644,238754.178830,429044.358673
12,Decision Tree,12,20,0.773300,247224.897013,431280.053932
13,Decision Tree,12,50,0.767820,249688.931823,436461.499687
14,Decision Tree,12,100,0.756957,254642.375918,446554.550415
8,Decision Tree,10,20,0.742458,271500.789764,459681.808030

#### **Random Forest**

In [15]:
from sklearn.ensemble import RandomForestRegressor

random_forest = RandomForestRegressor(
    n_estimators=50,
    max_depth=24,
    min_samples_leaf=50,
    random_state=42,
    n_jobs=-1
)


random_forest.fit(X_train_processed, y_train)

rf_pred = random_forest.predict(X_test_processed)

print("Random Forest model trained.")
print("Number of predictions:", len(rf_pred))
print("First 5 predictions:", rf_pred[:5])

Random Forest model trained.
Number of predictions: 11914
First 5 predictions: [ 809508.39089275  541208.72084892  314012.45691043 1699505.64635634
  699332.55233804]

In [17]:
rf_results = []

for n_estimators in [30, 50]:
    for max_depth in [12, 18, 24]:
        for min_samples_leaf in [10, 20, 50]:
            model = RandomForestRegressor(
                n_estimators=n_estimators,
                max_depth=max_depth,
                min_samples_leaf=min_samples_leaf,
                random_state=42,
                n_jobs=-1
            )
            
            model.fit(X_train_processed, y_train)
            pred = model.predict(X_test_processed)
            
            r2 = r2_score(y_test, pred)
            mae = mean_absolute_error(y_test, pred)
            rmse = np.sqrt(mean_squared_error(y_test, pred))
            
            rf_results.append({
                "Model": "Random Forest",
                "n_estimators": n_estimators,
                "max_depth": max_depth,
                "min_samples_leaf": min_samples_leaf,
                "R2": r2,
                "MAE": mae,
                "RMSE": rmse
            })

rf_tuning_results = pd.DataFrame(rf_results)
rf_tuning_results.sort_values("R2", ascending=False).head(10)

,Model,n_estimators,max_depth,min_samples_leaf,R2,MAE,RMSE
15,Random Forest,50,24,10,0.865646,173669.729391,332015.107951
6,Random Forest,30,24,10,0.865085,174160.276901,332708.359046
12,Random Forest,50,18,10,0.859977,181143.335899,338947.871623
3,Random Forest,30,18,10,0.859381,181643.995017,339668.962309
16,Random Forest,50,24,20,0.851572,183206.654457,348972.049542
7,Random Forest,30,24,20,0.851315,183742.704386,349275.027551
13,Random Forest,50,18,20,0.848602,187508.194859,352446.445680
4,Random Forest,30,18,20,0.848369,188009.406134,352718.093620
9,Random Forest,50,12,10,0.823711,217302.207579,380317.391846
0,Random Forest,30,12,10,0.823248,217655.534791,380816.183695

In [23]:

final_comparison = pd.DataFrame({
    "Experiment": [
        "Original Linear Regression",
        "No-Outlier Linear Regression",
        "Original Decision Tree",
        "No-Outlier Tuned Decision Tree",
        "Original Random Forest",
        "No-Outlier Tuned Random Forest"
    ],
    "Training Window": [
        "12 months",
        "12 months",
        "12 months",
        "12 months",
        "12 months",
        "12 months"
    ],
    "Test Month": [
        "2026-05",
        "2026-05",
        "2026-05",
        "2026-05",
        "2026-05",
        "2026-05"
    ],
    "R2": [
        0.2871733970446031,
        0.8415249235130129,
        -0.22783392239825506,
        0.814337,
        0.0340345465313624,
        0.865646
    ],
    "MAE": [
        452569.1626068585,
        220162.60581909068,
        538131.2198064434,
        211438.693273,
        371848.9678733415,
        173669.729391
    ],
    "RMSE": [
        1416770.3784853774,
        360590.0426259625,
        1859419.2911617595,
        390298.038735,
        1649256.9231636084,
        332015.107951
    ]
})

final_comparison

,Experiment,Training Window,Test Month,R2,MAE,RMSE
0,Original Linear Regression,12 months,2026-05,0.287173,452569.162607,1.416770e+06
1,No-Outlier Linear Regression,12 months,2026-05,0.841525,220162.605819,3.605900e+05
2,Original Decision Tree,12 months,2026-05,-0.227834,538131.219806,1.859419e+06
3,No-Outlier Tuned Decision Tree,12 months,2026-05,0.814337,211438.693273,3.902980e+05
4,Original Random Forest,12 months,2026-05,0.034035,371848.967873,1.649257e+06
5,No-Outlier Tuned Random Forest,12 months,2026-05,0.865646,173669.729391,3.320151e+05

# Week 6 — Feature Engineering

In this section, I add new engineered features and compare model performance before and after adding them. I use the no-outlier train/test datasets from Week 5 because the no-outlier experiment showed much stronger and more stable model performance.

In [21]:
week6_train_df = train_df.copy()
week6_test_df = test_df.copy()

print("Week 6 train shape:", week6_train_df.shape)
print("Week 6 test shape:", week6_test_df.shape)

Week 6 train shape: (128568, 57)
Week 6 test shape: (11914, 57)

In [22]:
week6_train_df["CloseDate"] = pd.to_datetime(week6_train_df["CloseDate"])
week6_test_df["CloseDate"] = pd.to_datetime(week6_test_df["CloseDate"])

print(week6_train_df["CloseDate"].dtype)
print(week6_test_df["CloseDate"].dtype)

datetime64[ns]
datetime64[ns]

In [26]:
week6_train_df.columns

Index(['ListingKey', 'CloseDate', 'close_year_month', '_source_file',
       'ClosePrice', 'LivingArea', 'BedroomsTotal', 'BathroomsTotalInteger',
       'LotSizeSquareFeet', 'LotSizeAcres', 'LotSizeArea', 'YearBuilt',
       'DaysOnMarket', 'GarageSpaces', 'ParkingTotal', 'OriginalListPrice',
       'ListPrice', 'Latitude', 'Longitude', 'Stories', 'AssociationFee',
       'MainLevelBedrooms', 'CountyOrParish', 'City', 'PostalCode',
       'HighSchoolDistrict', 'Flooring', 'AttachedGarageYN', 'Levels',
       'PoolPrivateYN', 'NewConstructionYN', 'ViewYN', 'FireplaceYN',
       'LivingArea_missing_flag', 'BedroomsTotal_missing_flag',
       'BathroomsTotalInteger_missing_flag', 'LotSizeSquareFeet_missing_flag',
       'LotSizeAcres_missing_flag', 'LotSizeArea_missing_flag',
       'YearBuilt_missing_flag', 'DaysOnMarket_missing_flag',
       'GarageSpaces_missing_flag', 'ParkingTotal_missing_flag',
       'OriginalListPrice_missing_flag', 'ListPrice_missing_flag',
       'Latitude_missing_flag', 'Longitude_missing_flag',
       'Stories_missing_flag', 'AssociationFee_missing_flag',
       'MainLevelBedrooms_missing_flag', 'price_per_sqft', 'log_LivingArea',
       'sale_year', 'home_age', 'log_ClosePrice', 'log_LotSizeSquareFeet',
       'home_age_missing_flag'],
      dtype='object')

In [33]:
def add_week6_basic_features(df):
    df = df.copy()

    # Bedroom-to-bathroom ratio 
    df["bed_bath_ratio"] = df["BedroomsTotal"] / df["BathroomsTotalInteger"].replace(0, np.nan)
    df["bed_bath_ratio_missing_flag"] = df["bed_bath_ratio"].isna().astype(int)

    # Living area per bedroom 
    df["living_area_per_bedroom"] = df["LivingArea"] / df["BedroomsTotal"].replace(0, np.nan)
    df["living_area_per_bedroom_missing_flag"] = df["living_area_per_bedroom"].isna().astype(int)

    # Lot size compare to living area
    df["lot_to_living_area_ratio"] = df["LotSizeSquareFeet"] / df["LivingArea"].replace(0, np.nan)
    df["lot_to_living_area_ratio_missing_flag"] = df["lot_to_living_area_ratio"].isna().astype(int)

    # Garage spaces per bedroom 
    df["garage_per_bedroom"] = df["GarageSpaces"] / df["BedroomsTotal"].replace(0, np.nan)
    df["garage_per_bedroom_missing_flag"] = df["garage_per_bedroom"].isna().astype(int)

    return df

In [34]:
week6_train_df = add_week6_basic_features(week6_train_df)
week6_test_df = add_week6_basic_features(week6_test_df)

print("Week 6 train shape after new features:", week6_train_df.shape)
print("Week 6 test shape after new features:", week6_test_df.shape)

Week 6 train shape after new features: (128568, 65)
Week 6 test shape after new features: (11914, 65)

In [35]:
week6_new_numeric_features = [
    'bed_bath_ratio', 
    'living_area_per_bedroom',
    'lot_to_living_area_ratio',
    'garage_per_bedroom'
]

for col in week6_new_numeric_features:
    train_median = week6_train_df[col].mean()

    week6_train_df[col] = week6_train_df[col].fillna(train_median)
    week6_test_df[col] = week6_test_df[col].fillna(train_median)

    print(col, "train median used:", train_median)

bed_bath_ratio train median used: 1.460948543218041
living_area_per_bedroom train median used: 575.08202301161
lot_to_living_area_ratio train median used: 208.2762359110007
garage_per_bedroom train median used: 0.5904012285487967

In [36]:
week6_train_df[
    [
        "BedroomsTotal",
        "BathroomsTotalInteger",
        "LivingArea",
        "LotSizeSquareFeet",
        "GarageSpaces",
        "bed_bath_ratio",
        "living_area_per_bedroom",
        "lot_to_living_area_ratio",
        "garage_per_bedroom"
    ]
].head()

,BedroomsTotal,BathroomsTotalInteger,LivingArea,LotSizeSquareFeet,GarageSpaces,bed_bath_ratio,living_area_per_bedroom,lot_to_living_area_ratio,garage_per_bedroom
0,3.0,2.0,1427.0,7000.0,2.0,1.50,475.666667,4.905396,0.666667
1,4.0,2.0,2148.0,5834.0,2.0,2.00,537.000000,2.716015,0.500000
2,4.0,4.0,2939.0,7108.0,2.0,1.00,734.750000,2.418510,0.500000
3,3.0,2.0,1520.0,11326.0,2.0,1.50,506.666667,7.451316,0.666667
4,5.0,4.0,3254.0,7584.0,3.0,1.25,650.800000,2.330670,0.600000

In [44]:
week6_new_features = [
    "bed_bath_ratio",
    "living_area_per_bedroom",
    "lot_to_living_area_ratio",
    "garage_per_bedroom"
]

week_6_new_missing_flag = [
    "bed_bath_ratio_missing_flag",
    "living_area_per_bedroom_missing_flag",
    "lot_to_living_area_ratio_missing_flag",
    "garage_per_bedroom_missing_flag"
]

week6_numeric_features = feature_numeric.copy()

for col in week6_new_features + week_6_new_missing_flag:
    if col in week6_train_df.columns and col not in week6_numeric_features:
        week6_numeric_features.append(col)

week6_categorical_features = feature_categorical.copy()

print("Original numeric features:", len(feature_numeric))
print("Week 6 numeric features:", len(week6_numeric_features))
print("Original categorial features:", len(feature_categorical))
print("Week 6 categorial features:", len(week6_categorical_features))

print("\nNew Week 6 numeric features added:")
for col in week6_numeric_features + week_6_new_missing_flag:
    if col in week6_numeric_features:
        print(col)

Original numeric features: 32
Week 6 numeric features: 40
Original categorial features: 11
Week 6 categorial features: 11

New Week 6 numeric features added:
LivingArea
BedroomsTotal
BathroomsTotalInteger
LotSizeSquareFeet
LotSizeAcres
LotSizeArea
YearBuilt
GarageSpaces
ParkingTotal
Latitude
Longitude
Stories
AssociationFee
MainLevelBedrooms
home_age
log_LivingArea
log_LotSizeSquareFeet
LivingArea_missing_flag
BedroomsTotal_missing_flag
BathroomsTotalInteger_missing_flag
LotSizeSquareFeet_missing_flag
LotSizeAcres_missing_flag
LotSizeArea_missing_flag
YearBuilt_missing_flag
GarageSpaces_missing_flag
ParkingTotal_missing_flag
Latitude_missing_flag
Longitude_missing_flag
Stories_missing_flag
AssociationFee_missing_flag
MainLevelBedrooms_missing_flag
home_age_missing_flag
bed_bath_ratio
living_area_per_bedroom
lot_to_living_area_ratio
garage_per_bedroom
bed_bath_ratio_missing_flag
living_area_per_bedroom_missing_flag
lot_to_living_area_ratio_missing_flag
garage_per_bedroom_missing_flag
bed_bath_ratio_missing_flag
living_area_per_bedroom_missing_flag
lot_to_living_area_ratio_missing_flag
garage_per_bedroom_missing_flag

In [45]:
week6_test_df

,ListingKey,CloseDate,close_year_month,_source_file,ClosePrice,LivingArea,BedroomsTotal,BathroomsTotalInteger,LotSizeSquareFeet,LotSizeAcres,...,log_LotSizeSquareFeet,home_age_missing_flag,bed_bath_ratio,bed_bath_ratio_missing_flag,living_area_per_bedroom,living_area_per_bedroom_missing_flag,lot_to_living_area_ratio,lot_to_living_area_ratio_missing_flag,garage_per_bedroom,garage_per_bedroom_missing_flag
0,1146592333,2026-05-01,2026-05,CRMLSSold202605.csv,885000.0,1124.0,3.0,2.0,7514.0,0.1725,...,8.924656,0,1.500000,0,374.666667,0,6.685053,0,0.666667,0
1,1152632400,2026-05-01,2026-05,CRMLSSold202605.csv,525000.0,1612.0,4.0,2.0,8160.0,0.1873,...,9.007122,0,2.000000,0,403.000000,0,5.062035,0,0.500000,0
2,1156060873,2026-05-01,2026-05,CRMLSSold202605.csv,315000.0,1314.0,3.0,2.0,16117.0,0.3700,...,9.687692,0,1.500000,0,438.000000,0,12.265601,0,1.333333,0
3,1136975543,2026-05-01,2026-05,CRMLSSold202605.csv,2100000.0,4365.0,4.0,4.0,11610.0,0.2665,...,9.359708,0,1.000000,0,1091.250000,0,2.659794,0,0.750000,0
4,1154111125,2026-05-01,2026-05,CRMLSSold202605.csv,645500.0,796.0,2.0,1.0,1883.0,0.0432,...,7.541152,0,2.000000,0,398.000000,0,2.365578,0,0.500000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,1157416320,2026-05-30,2026-05,CRMLSSold202605.csv,1350000.0,1692.0,4.0,3.0,2782.0,0.0639,...,7.931285,0,1.333333,0,423.000000,0,1.644208,0,0.500000,0
11910,1171037942,2026-05-30,2026-05,CRMLSSold202605.csv,595000.0,1845.0,3.0,2.0,7569.0,0.1738,...,8.931948,0,1.500000,0,615.000000,0,4.102439,0,0.666667,0
11911,1155431763,2026-05-31,2026-05,CRMLSSold202605.csv,656000.0,1059.0,3.0,2.0,6105.0,0.1402,...,8.717027,0,1.500000,0,353.000000,0,5.764873,0,0.666667,0
11912,1147756603,2026-05-31,2026-05,CRMLSSold202605.csv,985000.0,1748.0,3.0,2.0,7310.0,0.1678,...,8.897135,0,1.500000,0,582.666667,0,4.181922,0,0.666667,0
11913,1154154121,2026-05-31,2026-05,CRMLSSold202605.csv,1000000.0,2370.0,3.0,3.0,1089000.0,25.0000,...,13.900771,0,1.000000,0,790.000000,0,459.493671,0,0.000000,0

In [46]:
X_train_week6 = week6_train_df[week6_numeric_features + week6_categorical_features].copy()
X_test_week6 = week6_test_df[week6_numeric_features + week6_categorical_features].copy()

y_train_week6 = week6_train_df["ClosePrice"].copy()
y_test_week6 = week6_test_df["ClosePrice"].copy()

print("x_train_week6 shape", X_train_week6.shape)
print("X_test_week6 shape", X_test_week6.shape)
print("y_train_week6 shape,", y_train_week6.shape)
print("y_test_week6 shape,", y_test_week6.shape)

x_train_week6 shape (128568, 51)
X_test_week6 shape (11914, 51)
y_train_week6 shape, (128568,)
y_test_week6 shape, (11914,)

In [48]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

for col in week6_categorical_features:
    X_train_week6[col] = X_train_week6[col].astype(str)
    X_test_week6[col] = X_test_week6[col].astype(str)

try:
    encoder_week6 = OneHotEncoder(
        handle_unknown="ignore", # if the test set has a category that was not seen in training, do not crash
        sparse_output=True # stores inly the important non-zero values 
    )
except TypeError:
    encoder_week6 = OneHotEncoder(
        handle_unknown="ignore",
        sparse=True
    )

preprocessor_week6 = ColumnTransformer(
    transformers=[
        ("num", "passthrough", week6_numeric_features), # keep the numeric the same 
        ("cat", encoder_week6, week6_categorical_features) # apply one-hot encoding for categorical
    ],
    remainder="drop"
)

X_train_week6_processed = preprocessor_week6.fit_transform(X_train_week6)
X_test_week6_processed = preprocessor_week6.transform(X_test_week6)

print("Processed train shape:", X_train_week6_processed.shape)
print("Processed test shape:", X_test_week6_processed.shape)
print("Data type:", type(X_train_week6_processed))

Processed train shape: (128568, 3897)
Processed test shape: (11914, 3897)
Data type: <class 'scipy.sparse._csr.csr_matrix'>

In [49]:
rf_week6_results = []

for n_estimators in [30, 50]:
    for max_depth in [12, 18, 24]:
        for min_samples_leaf in [10, 20, 50]:
            model = RandomForestRegressor(
                n_estimators=n_estimators,
                max_depth=max_depth,
                min_samples_leaf=min_samples_leaf,
                random_state=42,
                n_jobs=-1
            )
            
            model.fit(X_train_week6_processed, y_train_week6)
            pred = model.predict(X_test_week6_processed)
            
            r2 = r2_score(y_test_week6, pred)
            mae = mean_absolute_error(y_test_week6, pred)
            rmse = np.sqrt(mean_squared_error(y_test_week6, pred))
            
            rf_week6_results.append({
                "Model": "Random Forest - Week 6 Features",
                "n_estimators": n_estimators,
                "max_depth": max_depth,
                "min_samples_leaf": min_samples_leaf,
                "R2": r2,
                "MAE": mae,
                "RMSE": rmse
            })

rf_week6_tuning_results = pd.DataFrame(rf_week6_results)
rf_week6_tuning_results.sort_values("R2", ascending=False).head(10)

,Model,n_estimators,max_depth,min_samples_leaf,R2,MAE,RMSE
15,Random Forest - Week 6 Features,50,24,10,0.860969,175681.694549,337745.210749
6,Random Forest - Week 6 Features,30,24,10,0.860636,176364.785612,338149.290083
12,Random Forest - Week 6 Features,50,18,10,0.856023,182561.962257,343700.671561
3,Random Forest - Week 6 Features,30,18,10,0.855820,183198.265207,343942.192985
16,Random Forest - Week 6 Features,50,24,20,0.847876,185107.883618,353290.970832
7,Random Forest - Week 6 Features,30,24,20,0.847186,185927.012720,354090.499133
13,Random Forest - Week 6 Features,50,18,20,0.844858,189368.463830,356778.106909
4,Random Forest - Week 6 Features,30,18,20,0.844254,190122.032716,357471.162893
0,Random Forest - Week 6 Features,30,12,10,0.821295,218462.023501,382913.911378
9,Random Forest - Week 6 Features,50,12,10,0.821220,218122.763985,382994.504520

In [51]:
week6_comparison = pd.DataFrame({
    "Model": [
        "Random Forest - Week 5 Features",
        "Random Forest - Week 6 Features"
    ],
    "Feature Set": [
        "Original no-outlier feature set",
        "Original features + engineered ratio features"
    ],
    "R2": [
        0.865646,
        0.860969
    ],
    "MAE": [
        173669.729391,
        175681.694549
    ],
    "RMSE": [
        332015.107951,
        337745.210749
    ]
})

week6_comparison

,Model,Feature Set,R2,MAE,RMSE
0,Random Forest - Week 5 Features,Original no-outlier feature set,0.865646,173669.729391,332015.107951
1,Random Forest - Week 6 Features,Original features + engineered ratio features,0.860969,175681.694549,337745.210749

### **Adding more detailed geographic layer using school districts**

In [52]:
import geopandas as gpd
from shapely.geometry import Point

In [53]:
school_districts_url = "https://gis.data.ca.gov/api/download/v1/items/b0e3b936426a47ce9d9a2e77e2bb86cc/geojson?layers=0"

school_districts = gpd.read_file(school_districts_url)

print("School districts shape:", school_districts.shape)
print("CRS:", school_districts.crs)

school_districts.head()

School districts shape: (937, 54)
CRS: EPSG:4326

,OBJECTID,Year,FedID,CDCode,CDSCode,CountyName,DistrictName,DistrictType,GradeLow,GradeHigh,...,MIGcount,MIGpct,SWDcount,SWDpct,SEDcount,SEDpct,DistrctAreaSqMi,Shape__Area,Shape__Length,geometry
0,1,2024-25,0601770,0161119,01611190000000,Alameda,Alameda Unified,Unified,PK,12,...,0,0.0,1356,12.6,3958,36.7,11.248939,4.755489e+07,56522.982683,"MULTIPOLYGON (((-122.22678 37.72651, -122.2267..."
1,2,2024-25,0601860,0161127,01611270000000,Alameda,Albany City Unified,Unified,PK,12,...,0,0.0,357,9.7,1184,32.1,1.789984,7.096327e+06,12696.382797,"POLYGON ((-122.28671 37.89852, -122.28673 37.8..."
2,3,2024-25,0604740,0161143,01611430000000,Alameda,Berkeley Unified,Unified,PK,12,...,0,0.0,1111,12.1,2686,29.3,10.434329,4.364648e+07,43695.341538,"POLYGON ((-122.25606 37.89834, -122.25607 37.8..."
3,4,2024-25,0607800,0161150,01611500000000,Alameda,Castro Valley Unified,Unified,PK,12,...,0,0.0,1113,11.6,3728,39.0,66.885571,2.838285e+08,142492.767565,"MULTIPOLYGON (((-122.01375 37.64265, -122.0114..."
4,5,2024-25,0612630,0161168,01611680000000,Alameda,Emery Unified,Unified,PK,12,...,0,0.0,81,13.7,412,69.8,1.273929,5.363392e+06,13741.272894,"POLYGON ((-122.29663 37.8311, -122.29778 37.83..."

In [54]:
school_districts.columns
[col for col in school_districts.columns if "district" in col.lower() or "name" in col.lower() or "type" in col.lower()]

['CountyName', 'DistrictName', 'DistrictType']

In [55]:
school_districts.columns

Index(['OBJECTID', 'Year', 'FedID', 'CDCode', 'CDSCode', 'CountyName',
       'DistrictName', 'DistrictType', 'GradeLow', 'GradeHigh',
       'GradeLowCensus', 'GradeHighCensus', 'AssistStatus', 'CongressUS',
       'SenateCA', 'AssemblyCA', 'UpdateNotes', 'EnrollTotal', 'EnrollCharter',
       'EnrollNonCharter', 'AAcount', 'AApct', 'AIcount', 'AIpct', 'AScount',
       'ASpct', 'FIcount', 'FIpct', 'HIcount', 'HIpct', 'PIcount', 'PIpct',
       'WHcount', 'WHpct', 'MRcount', 'MRpct', 'NRcount', 'NRpct', 'ELcount',
       'ELpct', 'FOScount', 'FOSpct', 'HOMcount', 'HOMpct', 'MIGcount',
       'MIGpct', 'SWDcount', 'SWDpct', 'SEDcount', 'SEDpct', 'DistrctAreaSqMi',
       'Shape__Area', 'Shape__Length', 'geometry'],
      dtype='object')

In [56]:
school_districts["DistrictType"].value_counts(dropna=False)

DistrictType
Elementary    516
Unified       345
High           76
Name: count, dtype: int64

The school district boundary file includes Elementary, High, and Unified district types. Elementary and High school district boundaries can overlap, which means joining all district types at once could create duplicate property rows if one property belongs to both an elementary and a high school district.

To keep the first version of the school district feature simple and clean, I filtered the boundary layer to Unified districts only. Unified districts generally cover both elementary and high school grade levels, so this provides a single school district label for matched properties and reduces the risk of duplicate rows.

In [57]:
unified_districts = school_districts[
    school_districts["DistrictType"] == "Unified"
].copy()


print("Unified districts shape:", unified_districts.shape)
unified_districts[["CountyName", "DistrictName", "DistrictType"]].head()

Unified districts shape: (345, 54)

  CountyName           DistrictName DistrictType
0    Alameda        Alameda Unified      Unified
1    Alameda    Albany City Unified      Unified
2    Alameda       Berkeley Unified      Unified
3    Alameda  Castro Valley Unified      Unified
4    Alameda          Emery Unified      Unified

### **Convert properties into map points**

In [58]:
train_geo = gpd.GeoDataFrame(
    week6_train_df.copy(),
    geometry=gpd.points_from_xy(week6_train_df["Longitude"], week6_train_df["Latitude"]),
    crs="EPSG:4326"
)

test_geo = gpd.GeoDataFrame(
    week6_test_df.copy(),
    geometry=gpd.points_from_xy(week6_test_df["Longitude"], week6_test_df["Latitude"]),
    crs="EPSG:4326"
)

print("Train CRS:", train_geo.crs)
print("Test CRS:", test_geo.crs)
print("Unified districts CRS:", unified_districts.crs)

Train CRS: EPSG:4326
Test CRS: EPSG:4326
Unified districts CRS: EPSG:4326

In [59]:
# Make sure both layers use the same coordinate system
unified_districts = unified_districts.to_crs(train_geo.crs)

print("Train CRS:", train_geo.crs)
print("Unified districts CRS:", unified_districts.crs)

Train CRS: EPSG:4326
Unified districts CRS: EPSG:4326